Cost:
  Name: ECG_processed
  avg_time: 14
  mean_time: 5
  n_samples: 5
  time: 90
Optimization:
  GP: Regular
  acquisition: qei
  device: cuda
  kernel_function: se
  model_save_path: models/
  n_exploration: 3
  n_parms: 2
  n_start_points: 3
  n_steps: 15
  range:
  - - 0
    - 85
  - - 0
    - 85
  range_cost:
  - 0
  - 50
