Cost:
  Name: "ECG_processed"        # name of the cost function stream
  time: 10 # time of the cost function stream.
  n_samples: 5
  avg_time: 14 # average time of the cost function stream.
  mean_time: 5 # mean time of the cost function.

Optimization:
  n_parms: 2 # number of parameters
  n_steps: 10 # number of steps
  n_exploration: 3 # number of exploration steps
  range: '[[10.0, 25.0], [10.0, 40.0]]' # range of the parameters
  model_save_path: "models/"
  device: "cuda" # device to use
  n_start_points: 3 # number of start points
  acquisition: 'qei'
  kernel_function: 'se'
  GP: "Regular"

# communication to the UI
Communication:
  Sending: True
  RECEIVING: True
  IP: "tcp://192.168.1.49"
  # This is inside the HIL function
  HIL:
    Cost_samples: 
      NAME: "Cost_samples"
      TYPE: "send"
      PORT: 4501
    FLAGS:
      NAME: "FLAGS"
      TYPE: "send"
      PORT: 4507
    STATUS:
      NAME: "STATUS"
      TYPE: "receive"
      PORT: 4508

  # in the BO function
  BO:
    Cost_GP:
      NAME: "Cost_GP"
      TYPE: "send"
      PORT: 4502
    
    Acquisition:
      NAME: "Acquisition"
      TYPE: "send"
      PORT: 4503
      
    Hyperparms:
      NAME: "Hyperparms"
      TYPE: "send"
      PORT: 4504

  # in the cost function 
  Raw_Cost:
    NAME: "Raw_Cost"
    TYPE:  "send"
    PORT: 4505

  Cost_steady_state_estimate:
    NAME: "Cost_steady_state_estimate"
    TYPE: "send"
    PORT: 4506
    
    
  # in stream data 
  Biosignals:
    first:
      NAME: "Raw_ecg"
      TYPE: "send"
      PORT: 4509
    
    second:
      NAME: "heart_rate"
      TYPE: "send"
      PORT: 4510
  
    

    

