Cost:
  Name: ECG_processed
  avg_time: 12
  mean_time: 5
  n_samples: 5
  time: 90
Optimization:
  GP: Regular
  acquisition: ei
  device: cuda
  kernel_function: se
  model_save_path: models/
  n_exploration: 3
  n_parms: 2
  n_start_points: 3
  n_steps: 15
  range:
  - - 0
    - 84
  - - 0
    - 84
